import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'; // Bootstrap CSS dosyası
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import StoreProvider from "./StoreProvider";
import {items} from "./menuItems";
config.autoAddCss = false
const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={outfit.className}>
        <Header menuItems={items}/>
        {children}
        <Footer/>
      </body>
    </html>
    </StoreProvider>
  );
}
